# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'veceleDesign.ui',
# licensing of 'veceleDesign.ui' applies.
#
# Created: Thu Jul 18 09:55:08 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.WVideo = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WVideo.sizePolicy().hasHeightForWidth())
        self.WVideo.setSizePolicy(sizePolicy)
        self.WVideo.setObjectName("WVideo")
        self.verticalLayout_3.addWidget(self.WVideo)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tlTempsPasser = QtWidgets.QLabel(self.centralwidget)
        self.tlTempsPasser.setObjectName("tlTempsPasser")
        self.horizontalLayout_2.addWidget(self.tlTempsPasser)
        self.hsTemps = QtWidgets.QSlider(self.centralwidget)
        self.hsTemps.setOrientation(QtCore.Qt.Horizontal)
        self.hsTemps.setObjectName("hsTemps")
        self.horizontalLayout_2.addWidget(self.hsTemps)
        self.tlTempsRestant = QtWidgets.QLabel(self.centralwidget)
        self.tlTempsRestant.setObjectName("tlTempsRestant")
        self.horizontalLayout_2.addWidget(self.tlTempsRestant)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbLecture = QtWidgets.QPushButton(self.centralwidget)
        self.pbLecture.setObjectName("pbLecture")
        self.horizontalLayout.addWidget(self.pbLecture)
        self.pbPause = QtWidgets.QPushButton(self.centralwidget)
        self.pbPause.setObjectName("pbPause")
        self.horizontalLayout.addWidget(self.pbPause)
        self.pbStop = QtWidgets.QPushButton(self.centralwidget)
        self.pbStop.setObjectName("pbStop")
        self.horizontalLayout.addWidget(self.pbStop)
        self.pbPrecedent = QtWidgets.QPushButton(self.centralwidget)
        self.pbPrecedent.setObjectName("pbPrecedent")
        self.horizontalLayout.addWidget(self.pbPrecedent)
        self.pbSuivant = QtWidgets.QPushButton(self.centralwidget)
        self.pbSuivant.setObjectName("pbSuivant")
        self.horizontalLayout.addWidget(self.pbSuivant)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listView = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pbAjoutFilm = QtWidgets.QPushButton(self.centralwidget)
        self.pbAjoutFilm.setObjectName("pbAjoutFilm")
        self.horizontalLayout_4.addWidget(self.pbAjoutFilm)
        self.pbSuppressionFilm = QtWidgets.QPushButton(self.centralwidget)
        self.pbSuppressionFilm.setObjectName("pbSuppressionFilm")
        self.horizontalLayout_4.addWidget(self.pbSuppressionFilm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setObjectName("dial")
        self.horizontalLayout_3.addWidget(self.dial)
        self.lpourcentageVolume = QtWidgets.QLabel(self.centralwidget)
        self.lpourcentageVolume.setObjectName("lpourcentageVolume")
        self.horizontalLayout_3.addWidget(self.lpourcentageVolume)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.tlTempsPasser.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.tlTempsRestant.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.pbLecture.setText(QtWidgets.QApplication.translate("MainWindow", "Lecture", None, -1))
        self.pbPause.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.pbStop.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.pbPrecedent.setText(QtWidgets.QApplication.translate("MainWindow", "Précédent", None, -1))
        self.pbSuivant.setText(QtWidgets.QApplication.translate("MainWindow", "Suivant", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Liste de lecture", None, -1))
        self.pbAjoutFilm.setText(QtWidgets.QApplication.translate("MainWindow", "+", None, -1))
        self.pbSuppressionFilm.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Volume", None, -1))
        self.lpourcentageVolume.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.menuFichier.setTitle(QtWidgets.QApplication.translate("MainWindow", "Fichier", None, -1))
        self.menuAide.setTitle(QtWidgets.QApplication.translate("MainWindow", "Aide", None, -1))

